extends Node

# --- 敵（ウェーブ）関連のベース設定 ---
var BASE_ENEMY_SPEED_NORMAL = 100.0
var BASE_ENEMY_HEALTH_NORMAL = 3

var BASE_SCOUT_SPEED = 150.0
var BASE_SCOUT_HEALTH = 1

var BASE_TANK_SPEED = 50.0
var BASE_TANK_HEALTH = 10

var BASE_SHOOTER_SPEED = 80.0
var BASE_SHOOTER_HEALTH = 5

var SHOOTER_ATTACK_RANGE = 250.0
var SHOOTER_PROJECTILE_SPEED = 300.0

# --- ウェーブ関連 ---
var WAVE_DURATION = 60.0
var INTERVAL_DURATION = 20.0
var BASE_ENEMY_SPAWN_INTERVAL = 3.0
var MIN_ENEMY_SPAWN_INTERVAL = 1.0
# ウェーブごとの強化倍率の上がり幅 (例: +0.2 = 20%アップ/ウェーブ)
var WAVE_DIFFICULTY_MULTIPLIER_STEP = 0.2

# --- アイテム関連 ---
var BASE_ITEM_SCORE = 100
var BASE_ITEM_WEIGHT = 1.0
var SCORE_INCREASE_PER_WAVE = 50
var WEIGHT_INCREASE_PER_WAVE = 0.2

var MAGNET_RADIUS = 120.0
var MAGNET_SPEED = 300.0
